### ISSUE TITLE
Can't sign in with google

### ISSUE THREAD

**Issue by elcampeon69** [GoogleCloudPlatform/firebase-android-client#24]
Hi!
i have a problem with the sign in option in Playchat. When i launch the application i can add my account with the sign in option from Google but the application doesn't log me. 
As a consequence i can't use Playchat.

Thanks for your help.

**Comment by ricalo** [comment]
Hi, @elcampeon69. Let me try to reproduce this issue from a new GCP Project. Any additional information is welcome. For example:

* What do you see in the app after you add your account?

Thank you.

**Comment by ricalo** [comment]
I was able to reproduce with a new Android Studio environment. The SHA certificate fingerprint of the new environment has not been registered in the Firebase Console. In this case, the authentication request is canceled. The app doesn't report this error, but logcat should report a message similar to the following:

```
Status{statusCode=CANCELED, resolution=null}
```

I added a condition to check if the authentication request was canceled in #25. Please take a look and let me know if this solves your issue.

**Comment by ricalo** [comment]
Not actionable anymore. Closing.
